export const SKILLS = [
    {
        id:1,
        name:'Javascript',
        url:'skills/javascript.webp'
    },
    {
        id:2,
        name:'React',
        url:'/skills/react.webp'
    },
    {
        id:3,
        name:'Vue js',
        url:'skills/vue.webp'
    },
    {
        id:4,
        name:'HTML',
        url:'skills/html.webp'
    },
    {
        id:5,
        name:'CSS',
        url:'skills/css.webp'
    },
    {
        id:6,
        name:'Python',
        url:'skills/python.webp'
    },
    {
        id:7,
        name:'Django',
        url:'skills/django.webp'
    },
    {
        id:8,
        name:'Git/Github',
        url:'skills/git-github.webp'
    },
    {
        id:9,
        name:'Docker',
        url:'skills/docker.webp'
    },
    {
        id:10,
        name:'SQL',
        url:'skills/sql.webp'
    },
    {
        id:11,
        name:'GraphQl',
        url:'skills/graphql.webp'
    },
]