export const SKILLS = [
    {
        id:1,
        name:'Javascript',
        url:'skills/javascript.svg'
    },
    {
        id:2,
        name:'React',
        url:'/skills/react.svg'
    },
    {
        id:3,
        name:'Vue js',
        url:'skills/vue.svg'
    },
    {
        id:4,
        name:'HTML',
        url:'skills/html.svg'
    },
    {
        id:5,
        name:'CSS',
        url:'skills/css.svg'
    },
    {
        id:6,
        name:'Python',
        url:'skills/python.svg'
    },
    {
        id:7,
        name:'Django',
        url:'skills/django.svg'
    },
    {
        id:8,
        name:'Git/Github',
        url:'skills/git-github.svg'
    },
    {
        id:9,
        name:'Docker',
        url:'skills/docker.svg'
    },
    {
        id:10,
        name:'SQL',
        url:'skills/sql.png'
    },
]